### ISSUE TITLE
Paleta de Cores

### ISSUE THREAD

**Issue by rafaelleitedasilva** [rafaelleitedasilva/blogtext#12]
Precisamos definir qual será a paleta de cores utilizada no sistema, se seguirá o mesmo padrão do template ou se será feita uma do zero, além disso o sistema terá modo escuro?
- [x] Modo Escuro
- [x] Paleta de Cores

**Comment by EdilsonBaggio** [comment]
Se tiver modo escuro vai ficar top, porque ai não força muito a visão.

**Comment by rafaelleitedasilva** [comment]
![image](https://github.com/rafaelleitedasilva/blogtext/assets/69431917/642c51be-fa89-45b9-8932-b61ce8fc0ef4)

![image](https://github.com/rafaelleitedasilva/blogtext/assets/69431917/70214472-fe67-4cb6-af09-e3321be2d19e)

No quesito das cores estava pensando em usar uma paleta que puxasse um pouco para o Ciano, algo bem suave... para o modo escuro poderia ser algo seguindo esse padrão de cor ou algo totalmente diferente mais voltado para o cinza:

![image](https://github.com/rafaelleitedasilva/blogtext/assets/69431917/741e50e7-ac4d-453e-8829-66f846a749da)

![image](https://github.com/rafaelleitedasilva/blogtext/assets/69431917/433065f8-d604-424b-a46d-eda60f9cbe19)

**Comment by EdilsonBaggio** [comment]
Acho que a palheta de cores https://user-images.githubusercontent.com/69431917/271941524-741e50e7-ac4d-453e-8829-66f846a749da.png fica mais atraente para o site, deixar eles só preto e cinza acho que não vai ficar legal.

**Comment by rafaelleitedasilva** [comment]
Após debate essas foram as paletas escolhidas...

![image](https://github.com/rafaelleitedasilva/blogtext/assets/69431917/8d7a9ff3-976d-44a4-a0ba-f46abba8158a)
![image](https://github.com/rafaelleitedasilva/blogtext/assets/69431917/22500c72-3fc9-4fef-8276-fed4b1bbe526)
