### ISSUE TITLE
Página "Em Construção"

### ISSUE THREAD

**Issue by rafaelleitedasilva** [rafaelleitedasilva/blogtext#3]
- [x] Criar Layout de Página "Em Construção"
 - [x] Criar frontend de Página "Em Contrução"

**Comment by rafaelleitedasilva** [comment]
@andreparelho @EdilsonBaggio Segue ideia de layout para página "Em Construção":
Sugestões?

https://www.figma.com/file/WxfL4xJWPpnoCekxQMxYC5/BlogText?type=design&node-id=1%3A2&mode=design&t=57ms4752EDIGPnPE-1

**Comment by rafaelleitedasilva** [comment]
![image](https://github.com/rafaelleitedasilva/blogtext/assets/69431917/67ce58d0-d57b-463a-ab48-c30224c9e613)

**Comment by EdilsonBaggio** [comment]
Eu gostei de como vai ficar está tela, mas acho que mudaria o background para uma estante de livros. Tipo de uma biblioteca exemplo: https://br.freepik.com/fotos-vetores-gratis/background-livros#query=background%20livros&position=3&from_view=keyword&track=ais e mudaria a opacidade dele para destacar o input.

**Comment by rafaelleitedasilva** [comment]
Gostei dessa, daria para usar o espaço em branco para colocar o texto, o que acham?
![image](https://github.com/rafaelleitedasilva/blogtext/assets/69431917/be229ce5-16bc-41b1-9fef-b4e5077d3f08)

**Comment by andreparelho** [comment]
Será que criar um gif com um livro sendo escrito daria muito trampo?

**Comment by rafaelleitedasilva** [comment]
> Será que criar um gif com um livro sendo escrito daria muito trampo?

Acho que já deve ter algum Gif assim, vou tentar encontrar algum bom...

**Comment by EdilsonBaggio** [comment]
Se for o que entendi, já sei onde trocar fiz esse ajuste no iCap. /resources/views/vendor/mail/html/index.html eu troquei direto lá o arquivo. Não sei se isso muda na versão do laravel.

**Comment by rafaelleitedasilva** [comment]
Feita correção da imagem no email e BugFix de erro 500 ao confirmar email.
