### ISSUE TITLE
Criação da Home

### ISSUE THREAD

**Issue by rafaelleitedasilva** [rafaelleitedasilva/blogtext#6]
- [x] Criação e definição do layout
- [x] Desenvolvimento Básico/Inicial do Frontend
- [x] Desenvolvimento Básico/Inicial do Backend

**Comment by rafaelleitedasilva** [comment]
@EdilsonBaggio @andreparelho Segue link com ideia inicial de layout para home. Tentei pensar em algo bem simples e minimalista.

https://www.figma.com/file/WxfL4xJWPpnoCekxQMxYC5/BlogText?type=design&node-id=0%3A1&mode=design&t=57ms4752EDIGPnPE-1

**Comment by rafaelleitedasilva** [comment]
![image](https://github.com/rafaelleitedasilva/blogtext/assets/69431917/9aabac93-bbf9-495b-a493-831b78070d24)

**Comment by andreparelho** [comment]
Seria um menu do lado esquerdo?

**Comment by rafaelleitedasilva** [comment]
> Seria um menu do lado esquerdo? 

Isso, se bem q n vai ter tantos itens pra colocar no menu, então um superior também serviria eu acho

**Comment by EdilsonBaggio** [comment]
![image](https://github.com/rafaelleitedasilva/blogtext/assets/71347535/4fd950b4-489f-45e9-ac3a-9aee956b4946)
Mano estou com este erro aqui no meu local se poder ajudar.

**Comment by rafaelleitedasilva** [comment]
Esse erro é porque precisa rodar o composer update, depoisvai precisar gerar uma chave provavelmente com o comando:
php artisan key:generate

**Comment by EdilsonBaggio** [comment]
Blz, o composer eu rodei acho que faltava o php artisan key:generate

**Comment by rafaelleitedasilva** [comment]
Será realizada a repartição dessa issue para duas após o desenvolvimento da tela de Login e Cadastro:
- Uma focada para o desenvolvimento frontend
- E uma focada para o desenvolvimento backend
