### ISSUE TITLE
Configuração de Email na Vercel

### ISSUE THREAD

**Issue by rafaelleitedasilva** [rafaelleitedasilva/blogtext#8]
- [x] Configurar envio de email por SMTP utilizando o outlook
- [ ] Avaliar qual será o email padrão

**Comment by rafaelleitedasilva** [comment]
Por enquanto o email foi consigurado utilizando o meu pessoal, mas será necessário avaliar um email padão para envio de emails.

**Comment by EdilsonBaggio** [comment]
Normalmente é usado um naoresponda@dominio.com.br por padrão.

**Comment by rafaelleitedasilva** [comment]
Sim! Acho que a Vercel não disponibiliza um email com domínio igual outras plataformas, então vou tentar providenciar um que use outlook mesmo.

**Comment by rafaelleitedasilva** [comment]
E-mail: naoresponda.blogtext@outlook.com
